export interface GemeenteProfiel {
  naam: string;
  provincie: string;
  woningdrukScore: number;
  provinciaalBeleidScore: number;
  legesTotaalMin: number;
  legesTotaalMax: number;
  openheidsScore: number;
  doorlooptijdMaandenMin: number;
  doorlooptijdMaandenMax: number;
  verleendIn2024: number;
  lat: number;
  lon: number;
  beleidsroutes: string[];
  omgevingsvisieSamenvatting: string;
}

const RAW: Omit<GemeenteProfiel, "openheidsScore">[] = [
  {
    naam: "Amsterdam", provincie: "Noord-Holland",
    woningdrukScore: 95, provinciaalBeleidScore: 60,
    legesTotaalMin: 4500, legesTotaalMax: 7000,
    doorlooptijdMaandenMin: 24, doorlooptijdMaandenMax: 48,
    verleendIn2024: 3,
    lat: 52.3676, lon: 4.9041,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Amsterdam richt zich sterk op binnenstedelijke verdichting. Buitenstedelijke woningbouw wordt nagenoeg niet gefaciliteerd; omgevingsplanwijzigingen buiten bestaand stedelijk gebied kennen hoge weerstand.",
  },
  {
    naam: "Rotterdam", provincie: "Zuid-Holland",
    woningdrukScore: 90, provinciaalBeleidScore: 65,
    legesTotaalMin: 3500, legesTotaalMax: 5500,
    doorlooptijdMaandenMin: 18, doorlooptijdMaandenMax: 36,
    verleendIn2024: 5,
    lat: 51.9225, lon: 4.4792,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging", "VAB"],
    omgevingsvisieSamenvatting: "Rotterdam zet in op transformatie van kantoren en havengebieden naar wonen. De gemeente staat open voor creatieve bestemmingswijzigingen die bijdragen aan de woningbouwopgave van 50.000 woningen tot 2040.",
  },
  {
    naam: "Den Haag", provincie: "Zuid-Holland",
    woningdrukScore: 88, provinciaalBeleidScore: 65,
    legesTotaalMin: 4000, legesTotaalMax: 6000,
    doorlooptijdMaandenMin: 20, doorlooptijdMaandenMax: 40,
    verleendIn2024: 4,
    lat: 52.0705, lon: 4.3007,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Den Haag focust op binnenstedelijke inbreiding en transformatie van kantoorlocaties. Buitenstedelijke uitbreiding wordt beperkt door provinciaal Groene Hart-beleid.",
  },
  {
    naam: "Utrecht", provincie: "Utrecht",
    woningdrukScore: 92, provinciaalBeleidScore: 55,
    legesTotaalMin: 3800, legesTotaalMax: 5800,
    doorlooptijdMaandenMin: 24, doorlooptijdMaandenMax: 48,
    verleendIn2024: 2,
    lat: 52.0907, lon: 5.1214,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "De provincie Utrecht hanteert een strikt 'Ja, mits'-beleid voor woningbouw buiten bestaand stedelijk gebied. Bestemmingswijzigingen worden kritisch getoetst aan het Interim Omgevingsverordening.",
  },
  {
    naam: "Eindhoven", provincie: "Noord-Brabant",
    woningdrukScore: 85, provinciaalBeleidScore: 70,
    legesTotaalMin: 2500, legesTotaalMax: 4500,
    doorlooptijdMaandenMin: 12, doorlooptijdMaandenMax: 24,
    verleendIn2024: 8,
    lat: 51.4416, lon: 5.4697,
    beleidsroutes: ["Rood-voor-Rood", "VAB", "BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Noord-Brabant stimuleert actief woningbouw in de regio Eindhoven via de Brabantse Omgevingsvisie. Rood-voor-Rood en VAB-regelingen bieden concrete routes voor agrarische percelen.",
  },
  {
    naam: "Groningen", provincie: "Groningen",
    woningdrukScore: 80, provinciaalBeleidScore: 73,
    legesTotaalMin: 2000, legesTotaalMax: 3800,
    doorlooptijdMaandenMin: 10, doorlooptijdMaandenMax: 20,
    verleendIn2024: 7,
    lat: 53.2194, lon: 6.5665,
    beleidsroutes: ["VAB", "BOPA", "Omgevingsplanwijziging", "Plattelandswoning"],
    omgevingsvisieSamenvatting: "De provincie Groningen stimuleert woningbouw mede als onderdeel van het herstelbeleid na de aardbevingsschade. Doorlooptijden zijn relatief kort; de gemeente is actief in het faciliteren van aanvragen.",
  },
  {
    naam: "Tilburg", provincie: "Noord-Brabant",
    woningdrukScore: 78, provinciaalBeleidScore: 70,
    legesTotaalMin: 2200, legesTotaalMax: 4000,
    doorlooptijdMaandenMin: 12, doorlooptijdMaandenMax: 22,
    verleendIn2024: 6,
    lat: 51.5555, lon: 5.0913,
    beleidsroutes: ["Rood-voor-Rood", "VAB", "BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Tilburg heeft een actieve grondpolitiek en staat open voor woningbouw aan de stadsranden. Brabantse beleidsroutes zoals Rood-voor-Rood zijn goed toegankelijk via het regionaal omgevingsprogramma.",
  },
  {
    naam: "Almere", provincie: "Flevoland",
    woningdrukScore: 82, provinciaalBeleidScore: 85,
    legesTotaalMin: 2500, legesTotaalMax: 4000,
    doorlooptijdMaandenMin: 9, doorlooptijdMaandenMax: 18,
    verleendIn2024: 12,
    lat: 52.3508, lon: 5.2647,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging", "Zelfbouw"],
    omgevingsvisieSamenvatting: "Flevoland is de meest open provincie voor woningbouw. Almere heeft een ambitieuze groeistrategie en verleent actief medewerking aan woonbestemmingen. Doorlooptijden zijn kort en leges zijn relatief laag.",
  },
  {
    naam: "Breda", provincie: "Noord-Brabant",
    woningdrukScore: 76, provinciaalBeleidScore: 70,
    legesTotaalMin: 2200, legesTotaalMax: 4000,
    doorlooptijdMaandenMin: 12, doorlooptijdMaandenMax: 24,
    verleendIn2024: 5,
    lat: 51.5719, lon: 4.7683,
    beleidsroutes: ["Rood-voor-Rood", "VAB", "BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Breda wil 20.000 woningen toevoegen voor 2040. De gemeente werkt actief mee aan conversie van agrarische locaties nabij stedelijk gebied via de Brabantse beleidsroutes.",
  },
  {
    naam: "Nijmegen", provincie: "Gelderland",
    woningdrukScore: 79, provinciaalBeleidScore: 68,
    legesTotaalMin: 2400, legesTotaalMax: 4200,
    doorlooptijdMaandenMin: 14, doorlooptijdMaandenMax: 28,
    verleendIn2024: 5,
    lat: 51.8426, lon: 5.8546,
    beleidsroutes: ["Rood-voor-Rood", "VAB", "BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Gelderland biedt via de Omgevingsvisie Gaaf Gelderland concrete routes voor woningbouw in het buitengebied. Nijmegen heeft een hoge woningbehoefte en ondersteunt conversie-initiatieven actief.",
  },
  {
    naam: "Haarlem", provincie: "Noord-Holland",
    woningdrukScore: 87, provinciaalBeleidScore: 60,
    legesTotaalMin: 3500, legesTotaalMax: 5500,
    doorlooptijdMaandenMin: 20, doorlooptijdMaandenMax: 42,
    verleendIn2024: 2,
    lat: 52.3874, lon: 4.6462,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Haarlem is omgeven door Groene Hart en beschermde poldergebieden, wat buitenstedelijke bestemmingswijzigingen sterk beperkt. De gemeente focust op inbreiding en transformatie van bestaand bebouwd gebied.",
  },
  {
    naam: "Arnhem", provincie: "Gelderland",
    woningdrukScore: 75, provinciaalBeleidScore: 68,
    legesTotaalMin: 2200, legesTotaalMax: 3800,
    doorlooptijdMaandenMin: 12, doorlooptijdMaandenMax: 24,
    verleendIn2024: 6,
    lat: 51.9851, lon: 5.8987,
    beleidsroutes: ["Rood-voor-Rood", "VAB", "BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Arnhem en de regio Arnhem-Nijmegen kennen een stevige woningbouwopgave. De gemeente werkt samen met de provincie Gelderland aan locaties voor woonbestemming in de stadsrandzones.",
  },
  {
    naam: "Zaanstad", provincie: "Noord-Holland",
    woningdrukScore: 83, provinciaalBeleidScore: 60,
    legesTotaalMin: 2800, legesTotaalMax: 4800,
    doorlooptijdMaandenMin: 18, doorlooptijdMaandenMax: 36,
    verleendIn2024: 3,
    lat: 52.4567, lon: 4.8180,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging", "VAB"],
    omgevingsvisieSamenvatting: "Zaanstad heeft transformatiepotentieel langs de Zaan en op voormalige bedrijfsterreinen. Buitenstedelijke bestemmingswijzigingen worden beperkt door het stringente Noord-Hollandse Omgevingsbeleid.",
  },
  {
    naam: "Amersfoort", provincie: "Utrecht",
    woningdrukScore: 84, provinciaalBeleidScore: 55,
    legesTotaalMin: 2800, legesTotaalMax: 4800,
    doorlooptijdMaandenMin: 22, doorlooptijdMaandenMax: 42,
    verleendIn2024: 2,
    lat: 52.1551, lon: 5.3878,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "De provincie Utrecht stelt strenge eisen aan buitenstedelijke woningbouw. Amersfoort groeit primair via uitleglocaties als Vathorst; omgevingsplanwijzigingen in het buitengebied zijn lastig.",
  },
  {
    naam: "Apeldoorn", provincie: "Gelderland",
    woningdrukScore: 70, provinciaalBeleidScore: 68,
    legesTotaalMin: 2000, legesTotaalMax: 3500,
    doorlooptijdMaandenMin: 10, doorlooptijdMaandenMax: 22,
    verleendIn2024: 7,
    lat: 52.2112, lon: 5.9699,
    beleidsroutes: ["Rood-voor-Rood", "VAB", "BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Apeldoorn heeft een grote grondpositie in het buitengebied en is actief in het faciliteren van woningbouw op voormalige agrarische locaties. Rood-voor-Rood werkt goed in deze gemeente.",
  },
  {
    naam: "Enschede", provincie: "Overijssel",
    woningdrukScore: 68, provinciaalBeleidScore: 72,
    legesTotaalMin: 1800, legesTotaalMax: 3200,
    doorlooptijdMaandenMin: 10, doorlooptijdMaandenMax: 20,
    verleendIn2024: 6,
    lat: 52.2215, lon: 6.8937,
    beleidsroutes: ["Rood-voor-Rood", "VAB", "BOPA", "Kwaliteitsimpuls Groene Omgeving"],
    omgevingsvisieSamenvatting: "Overijssel hanteert de Kwaliteitsimpuls Groene Omgeving (KGO) als beleidsinstrument voor woningbouw in het buitengebied. Enschede staat open voor kwalitatief goede inbreidingsplannen.",
  },
  {
    naam: "s-Hertogenbosch", provincie: "Noord-Brabant",
    woningdrukScore: 77, provinciaalBeleidScore: 70,
    legesTotaalMin: 2300, legesTotaalMax: 4200,
    doorlooptijdMaandenMin: 12, doorlooptijdMaandenMax: 24,
    verleendIn2024: 6,
    lat: 51.6978, lon: 5.3037,
    beleidsroutes: ["Rood-voor-Rood", "VAB", "BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "'s-Hertogenbosch heeft een actieve woonagenda en werkt goed mee aan conversie van agrarische erven binnen de stedelijke invloedsfeer. De Brabantse beleidsroutes zijn goed toegankelijk.",
  },
  {
    naam: "Zwolle", provincie: "Overijssel",
    woningdrukScore: 74, provinciaalBeleidScore: 72,
    legesTotaalMin: 2000, legesTotaalMax: 3500,
    doorlooptijdMaandenMin: 10, doorlooptijdMaandenMax: 20,
    verleendIn2024: 7,
    lat: 52.5168, lon: 6.0830,
    beleidsroutes: ["Rood-voor-Rood", "VAB", "BOPA", "Kwaliteitsimpuls Groene Omgeving"],
    omgevingsvisieSamenvatting: "Zwolle en de regio hebben een stevige woningbouwopgave. De gemeente hanteert een actief facilitair beleid voor woonbestemmingen en de KGO-route werkt goed in het omliggende buitengebied.",
  },
  {
    naam: "Leiden", provincie: "Zuid-Holland",
    woningdrukScore: 86, provinciaalBeleidScore: 65,
    legesTotaalMin: 3500, legesTotaalMax: 5500,
    doorlooptijdMaandenMin: 20, doorlooptijdMaandenMax: 40,
    verleendIn2024: 3,
    lat: 52.1601, lon: 4.4970,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Leiden is omgeven door beschermd bollenlandschap en Groene Hart. De woningdruk is hoog maar buitenstedelijke bestemmingswijzigingen zijn complex door provinciaal en Rijksbeleid.",
  },
  {
    naam: "Dordrecht", provincie: "Zuid-Holland",
    woningdrukScore: 72, provinciaalBeleidScore: 65,
    legesTotaalMin: 2200, legesTotaalMax: 3800,
    doorlooptijdMaandenMin: 14, doorlooptijdMaandenMax: 28,
    verleendIn2024: 4,
    lat: 51.8133, lon: 4.6901,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging", "VAB"],
    omgevingsvisieSamenvatting: "Dordrecht heeft ruimte voor woningbouw op voormalige bedrijfslocaties en in de Drechtsteden-samenwerking. Agrarische conversie wordt beperkt door Groene Hart-bescherming.",
  },
  {
    naam: "Haarlemmermeer", provincie: "Noord-Holland",
    woningdrukScore: 88, provinciaalBeleidScore: 60,
    legesTotaalMin: 3000, legesTotaalMax: 5000,
    doorlooptijdMaandenMin: 18, doorlooptijdMaandenMax: 36,
    verleendIn2024: 4,
    lat: 52.3060, lon: 4.6889,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Haarlemmermeer groeit sterk als Schipholregio. De gemeente heeft ambitie voor woningbouw maar is gebonden aan provinciaal Noord-Hollands beleid dat buitenstedelijke uitbreiding sterk beperkt.",
  },
  {
    naam: "Delft", provincie: "Zuid-Holland",
    woningdrukScore: 82, provinciaalBeleidScore: 65,
    legesTotaalMin: 3200, legesTotaalMax: 5200,
    doorlooptijdMaandenMin: 18, doorlooptijdMaandenMax: 36,
    verleendIn2024: 3,
    lat: 52.0116, lon: 4.3571,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Delft focust op herontwikkeling van campuslocaties en voormalige spoor- en bedrijfsterreinen. Buitenstedelijke woningbouw is nagenoeg niet mogelijk door de ligging in de Randstad.",
  },
  {
    naam: "Westland", provincie: "Zuid-Holland",
    woningdrukScore: 75, provinciaalBeleidScore: 65,
    legesTotaalMin: 2800, legesTotaalMax: 4500,
    doorlooptijdMaandenMin: 16, doorlooptijdMaandenMax: 32,
    verleendIn2024: 3,
    lat: 51.9957, lon: 4.1972,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging", "Glastuinbouw-omvorming"],
    omgevingsvisieSamenvatting: "Westland heeft een bijzondere positie als glastuinbouwgemeente. Omvorming van verouderd glastuinbouwgebied naar wonen is een actief beleidsthema, maar kent specifieke provinciale randvoorwaarden.",
  },
  {
    naam: "Gouda", provincie: "Zuid-Holland",
    woningdrukScore: 74, provinciaalBeleidScore: 65,
    legesTotaalMin: 2400, legesTotaalMax: 4000,
    doorlooptijdMaandenMin: 14, doorlooptijdMaandenMax: 28,
    verleendIn2024: 4,
    lat: 52.0116, lon: 4.7062,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging", "VAB"],
    omgevingsvisieSamenvatting: "Gouda wil transformatielocaties en voormalige kantoorvastgoed omzetten naar wonen. Buitenstedelijk is de ruimte beperkt door het Groene Hart; de gemeente werkt actief met de provincie aan zoekgebieden.",
  },
  {
    naam: "Zoetermeer", provincie: "Zuid-Holland",
    woningdrukScore: 78, provinciaalBeleidScore: 65,
    legesTotaalMin: 3000, legesTotaalMax: 5000,
    doorlooptijdMaandenMin: 18, doorlooptijdMaandenMax: 36,
    verleendIn2024: 3,
    lat: 52.0606, lon: 4.4936,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Zoetermeer is een compacte stad met beperkte uitbreidingsruimte. De gemeente richt zich op binnenstedelijke verdichting en transformatie van kantoorparken langs de snelwegen.",
  },
  {
    naam: "Leeuwarden", provincie: "Friesland",
    woningdrukScore: 65, provinciaalBeleidScore: 78,
    legesTotaalMin: 1800, legesTotaalMax: 3000,
    doorlooptijdMaandenMin: 9, doorlooptijdMaandenMax: 18,
    verleendIn2024: 8,
    lat: 53.2012, lon: 5.7999,
    beleidsroutes: ["VAB", "BOPA", "Omgevingsplanwijziging", "Plattelandswoning"],
    omgevingsvisieSamenvatting: "Friesland heeft een open houding ten aanzien van woningbouw in het buitengebied. VAB-regelingen zijn goed toegankelijk en de doorlooptijden zijn kort. Leeuwarden werkt actief aan het behoud van leefbaarheid in kleinere kernen.",
  },
  {
    naam: "Middelburg", provincie: "Zeeland",
    woningdrukScore: 65, provinciaalBeleidScore: 80,
    legesTotaalMin: 1800, legesTotaalMax: 3000,
    doorlooptijdMaandenMin: 8, doorlooptijdMaandenMax: 16,
    verleendIn2024: 9,
    lat: 51.4988, lon: 3.6136,
    beleidsroutes: ["VAB", "BOPA", "Omgevingsplanwijziging", "Plattelandswoning", "Rood-voor-Rood"],
    omgevingsvisieSamenvatting: "Zeeland heeft de meest soepele houding voor woningbouw buiten bestaand bebouwd gebied. De provincie wil krimp tegengaan en stimuleert actief hergebruik van agrarische erven. Doorlooptijden zijn de kortste van Nederland.",
  },
  {
    naam: "Venlo", provincie: "Limburg",
    woningdrukScore: 67, provinciaalBeleidScore: 67,
    legesTotaalMin: 2000, legesTotaalMax: 3500,
    doorlooptijdMaandenMin: 12, doorlooptijdMaandenMax: 24,
    verleendIn2024: 5,
    lat: 51.3704, lon: 6.1724,
    beleidsroutes: ["VAB", "BOPA", "Omgevingsplanwijziging", "Limburgs Kwaliteitsmenu"],
    omgevingsvisieSamenvatting: "Limburg hanteert het Limburgs Kwaliteitsmenu (LKM) als afwegingskader voor woningbouw in het buitengebied. Venlo staat relatief open voor agrarische conversie mits gekoppeld aan landschapskwaliteitsverbetering.",
  },
  {
    naam: "Maastricht", provincie: "Limburg",
    woningdrukScore: 68, provinciaalBeleidScore: 67,
    legesTotaalMin: 2200, legesTotaalMax: 3800,
    doorlooptijdMaandenMin: 14, doorlooptijdMaandenMax: 28,
    verleendIn2024: 4,
    lat: 50.8514, lon: 5.6910,
    beleidsroutes: ["VAB", "BOPA", "Omgevingsplanwijziging", "Limburgs Kwaliteitsmenu"],
    omgevingsvisieSamenvatting: "Maastricht heeft door zijn grensligging en monumentale karakter een specifiek woningbouwbeleid. Het Limburgs Kwaliteitsmenu biedt ruimte voor conversie mits er landschappelijke tegenprestaties worden geleverd.",
  },
  {
    naam: "Deventer", provincie: "Overijssel",
    woningdrukScore: 70, provinciaalBeleidScore: 72,
    legesTotaalMin: 1800, legesTotaalMax: 3000,
    doorlooptijdMaandenMin: 10, doorlooptijdMaandenMax: 20,
    verleendIn2024: 7,
    lat: 52.2550, lon: 6.1566,
    beleidsroutes: ["Rood-voor-Rood", "VAB", "BOPA", "Kwaliteitsimpuls Groene Omgeving"],
    omgevingsvisieSamenvatting: "Deventer heeft een actief buitengebiedsbeleid via de KGO-route. De gemeente staat open voor woonbestemmingen op voormalige agrarische erven en werkt constructief mee aan initiatieven.",
  },
  {
    naam: "Roosendaal", provincie: "Noord-Brabant",
    woningdrukScore: 65, provinciaalBeleidScore: 70,
    legesTotaalMin: 1900, legesTotaalMax: 3200,
    doorlooptijdMaandenMin: 10, doorlooptijdMaandenMax: 22,
    verleendIn2024: 6,
    lat: 51.5303, lon: 4.4614,
    beleidsroutes: ["Rood-voor-Rood", "VAB", "BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Roosendaal is een middelgrote Brabantse gemeente met actieve inzet op woningbouw. Via Rood-voor-Rood en VAB zijn er concrete mogelijkheden voor agrarische conversie in het buitengebied.",
  },
  {
    naam: "De Ronde Venen", provincie: "Utrecht",
    woningdrukScore: 72, provinciaalBeleidScore: 55,
    legesTotaalMin: 2000, legesTotaalMax: 3500,
    doorlooptijdMaandenMin: 20, doorlooptijdMaandenMax: 40,
    verleendIn2024: 1,
    lat: 52.2330, lon: 4.8440,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "De Ronde Venen ligt grotendeels in het Groene Hart, het nationale beschermde veenweidelandschap. Woningbouw buiten bestaand bebouwd gebied stuit op zware Rijks- en provinciale beperkingen.",
  },
  {
    naam: "Woerden", provincie: "Utrecht",
    woningdrukScore: 70, provinciaalBeleidScore: 55,
    legesTotaalMin: 2200, legesTotaalMax: 3800,
    doorlooptijdMaandenMin: 20, doorlooptijdMaandenMax: 42,
    verleendIn2024: 1,
    lat: 52.0878, lon: 4.8881,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Woerden is volledig omgeven door Groene Hart. De provincie Utrecht en het Rijksbeleid laten nauwelijks ruimte voor buitenstedelijke woningbouw; aanvragen kennen hoge weerstand en lange doorlooptijden.",
  },
  {
    naam: "Stichtse Vecht", provincie: "Utrecht",
    woningdrukScore: 73, provinciaalBeleidScore: 55,
    legesTotaalMin: 2200, legesTotaalMax: 4000,
    doorlooptijdMaandenMin: 22, doorlooptijdMaandenMax: 42,
    verleendIn2024: 1,
    lat: 52.2266, lon: 5.0008,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging"],
    omgevingsvisieSamenvatting: "Stichtse Vecht is een groene uitloopgemeente met strakke provinciale beperkingen vanuit het Groene Hart en de Utrechtse Heuvelrug. Bestemmingswijzigingen in het buitengebied zijn uiterst moeilijk.",
  },
  {
    naam: "Katwijk", provincie: "Zuid-Holland",
    woningdrukScore: 76, provinciaalBeleidScore: 65,
    legesTotaalMin: 2400, legesTotaalMax: 4000,
    doorlooptijdMaandenMin: 16, doorlooptijdMaandenMax: 30,
    verleendIn2024: 4,
    lat: 52.2013, lon: 4.4028,
    beleidsroutes: ["BOPA", "Omgevingsplanwijziging", "VAB"],
    omgevingsvisieSamenvatting: "Katwijk heeft een groeiende woningbehoefte en is actief in kustgebonden herstructurering. De gemeente werkt mee aan conversie van bollengrond naar wonen binnen de kaders van het provinciale beleid.",
  },
  {
    naam: "Súdwest-Fryslân", provincie: "Friesland",
    woningdrukScore: 60, provinciaalBeleidScore: 78,
    legesTotaalMin: 1600, legesTotaalMax: 2800,
    doorlooptijdMaandenMin: 8, doorlooptijdMaandenMax: 16,
    verleendIn2024: 10,
    lat: 52.9966, lon: 5.6596,
    beleidsroutes: ["VAB", "BOPA", "Omgevingsplanwijziging", "Plattelandswoning", "Rood-voor-Rood"],
    omgevingsvisieSamenvatting: "Súdwest-Fryslân is de grootste gemeente van Friesland en heeft als kerntaak het behoud van leefbaarheid in het platteland. De gemeente is zeer actief in het faciliteren van woonbestemmingen op voormalige agrarische locaties.",
  },
];

export const GEMEENTEN: GemeenteProfiel[] = RAW.map((g) => ({
  ...g,
  openheidsScore: Math.round(g.woningdrukScore * 0.6 + g.provinciaalBeleidScore * 0.4),
})).sort((a, b) => b.openheidsScore - a.openheidsScore);

export const PROVINCIES = [...new Set(GEMEENTEN.map((g) => g.provincie))].sort();
